'use client';
import './globals.css';
import { Merriweather } from 'next/font/google';

const merriweather = Merriweather({
  weight: ['300', '700'],
  subsets: ['latin'],
});

import { Header } from '@/components/Header/Header';
import StyledComponentsRegistry from '@/lib/registry';
import { Box } from '@/components/Box/Box';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={merriweather.className} style={{ paddingTop: 80 }}>
        <StyledComponentsRegistry>
          <Box
            width="100%"
            display="flex"
            flexDirection="column"
            alignItems="center"
          >
            <Box width="100%" maxWidth={1440}>
              <Header />
              {children}
            </Box>
          </Box>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
